# Generated by Django 3.0.7 on 2020-06-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.CharField(default='twillo', max_length=50),
        ),
    ]
