# Generated by Django 3.0.7 on 2020-07-16 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='grouptoken',
        ),
    ]
