# Generated by Django 3.0.7 on 2020-06-30 04:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0002_user_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='sender',
        ),
        migrations.AddField(
            model_name='group',
            name='recipient',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.CreateModel(
            name='GroupUnique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.UUIDField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='groupID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grp_id', to='smsApp.GroupUnique'),
        ),
    ]
