# Generated by Django 3.0.7 on 2020-07-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0002_remove_message_grouptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='grouptoken',
            field=models.UUIDField(null=True),
        ),
    ]
