# Generated by Django 3.0.7 on 2020-07-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0002_auto_20200713_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='language',
            field=models.CharField(blank=True, choices=[('af', 'af'), ('sq', 'sq'), ('am', 'am'), ('ar', 'ar'), ('hy', 'hy'), ('az', 'az'), ('eu', 'eu'), ('be', 'be'), ('bn', 'bn'), ('bs', 'bs'), ('bg', 'bg'), ('ca', 'ca'), ('ceb', 'ceb'), ('ny', 'ny'), ('zh-cn', 'zh-cn'), ('zh-tw', 'zh-tw'), ('co', 'co'), ('hr', 'hr'), ('cs', 'cs'), ('da', 'da'), ('nl', 'nl'), ('en', 'en'), ('eo', 'eo'), ('et', 'et'), ('tl', 'tl'), ('fi', 'fi'), ('fr', 'fr'), ('fy', 'fy'), ('gl', 'gl'), ('ka', 'ka'), ('de', 'de'), ('el', 'el'), ('gu', 'gu'), ('ht', 'ht'), ('ha', 'ha'), ('haw', 'haw'), ('iw', 'iw'), ('hi', 'hin'), ('hmn', 'hmn'), ('hu', 'hu'), ('is', 'is'), ('ig', 'ig'), ('id', 'id'), ('ga', 'ga'), ('it', 'it'), ('ja', 'ja'), ('jw', 'jw'), ('kn', 'kn'), ('kk', 'kk'), ('km', 'km'), ('ko', 'ko'), ('ku', 'ku'), ('ky', 'ky'), ('lo', 'la'), ('la', 'la'), ('lv', 'lv'), ('lt', 'lt'), ('lb', 'lb'), ('mk', 'mk'), ('mg', 'mg'), ('ms', 'ms'), ('ml', 'ml'), ('mt', 'mt'), ('mi', 'mi'), ('mr', 'mr'), ('mn', 'mn'), ('my', 'my'), ('ne', 'ne'), ('no', 'no'), ('ps', 'ps'), ('fa', 'fa'), ('pl', 'pl'), ('pt', 'pt'), ('pa', 'pa'), ('ro', 'ro'), ('ru', 'ru'), ('sm', 'sm'), ('gd', 'gd'), ('sr', 'sr'), ('st', 'st'), ('sn', 'sn'), ('sd', 'si'), ('si', 'si'), ('sk', 'sk'), ('sl', 'sl'), ('so', 'so'), ('es', 'es'), ('su', 'su'), ('sw', 'sw'), ('sv', 'sv'), ('tg', 'tg'), ('ta', 'ta'), ('te', 'te'), ('th', 'th'), ('tr', 'tr'), ('uk', 'uk'), ('ur', 'ur'), ('uz', 'uz'), ('vi', 'vi'), ('cy', 'cy'), ('xh', 'xh'), ('yi', 'yi'), ('yo', 'yo'), ('zu', 'zu'), ('fil', 'Fil'), ('he', 'He')], default='en', max_length=5, null=True),
        ),
    ]
