# Generated by Django 3.0.7 on 2020-07-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0002_auto_20200709_0456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipent',
            new_name='Recipient',
        ),
    ]
