# Generated by Django 3.0.7 on 2020-07-16 00:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0003_message_grouptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messageID',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
