# Generated by Django 3.0.7 on 2020-07-10 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0002_auto_20200709_0215'),
        ('smsApp', '0003_auto_20200709_0540'),
    ]

    operations = [
    ]
