# Generated by Django 3.0.7 on 2020-06-30 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0003_auto_20200630_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groupName',
        ),
        migrations.RemoveField(
            model_name='groupunique',
            name='groupID',
        ),
        migrations.AddField(
            model_name='groupunique',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupunique',
            name='groupName',
            field=models.CharField(default='grp1', max_length=80),
        ),
    ]
