# Generated by Django 3.0.7 on 2020-07-09 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0004_merge_20200709_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnumbers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='smsApp.Group'),
        ),
    ]
