# Generated by Django 3.0.7 on 2020-07-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0004_message_messageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messageStatus',
            field=models.CharField(choices=[('D', 'D'), ('P', 'P'), ('S', 'S'), ('U', 'U'), ('F', 'F'), ('R', 'R'), ('SC', 'SC')], default='D', max_length=2),
        ),
    ]
