# Generated by Django 3.0.7 on 2020-07-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0005_auto_20200716_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messageStatus',
            field=models.CharField(choices=[('D', 'D'), ('P', 'P'), ('S', 'S'), ('U', 'U'), ('F', 'F'), ('E', 'E'), ('FR', 'FR'), ('R', 'R'), ('SC', 'SC')], default='D', max_length=2),
        ),
    ]
