# Generated by Django 3.0.7 on 2020-07-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0005_auto_20200709_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='grouptoken',
            field=models.UUIDField(null=True),
        ),
    ]
