# Generated by Django 3.0.7 on 2020-07-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0005_auto_20200716_1758'),
        ('smsApp', '0005_auto_20200716_2250'),
    ]

    operations = [
    ]
