# Generated by Django 3.0.7 on 2020-07-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0006_auto_20200718_1430'),
        ('smsApp', '0006_merge_20200718_1033'),
    ]

    operations = [
    ]
